### ISSUE TITLE
Coding system releases: overview

### ISSUE THREAD

**Issue by rebkwok** [opensafely-core/opencodelists#1446]
This issue is to track subtasks and progress on the coding system releases.  See also comments on the [initial investigation issue](https://github.com/opensafely-core/opencodelists/issues/1379).
- [ ] New release model and extraction of current coding system data to separate databases #1397
- [ ] Make coding system methods use the relevant separate databases #1401 
- [ ] #1411
- [ ] #1409
- [ ] #1441 
- [ ] #1421
- [ ] #1455
- [ ] #1433 (futher mapping questions)
