### ISSUE TITLE
Short-term solution for superceded dm+d codes

### ISSUE THREAD

**Issue by rebkwok** [opensafely-core/opencodelists#1449]
Problem:
dm+d VMP IDs can change.  When they do, they have a previous VMP ID recorded against them.  If a codelist contains only the current ID, or only the previous ID, queries on `with_these_medications` will fail to match all relevant matching medications.

dm+d codelists are "old style" codelists. Updating them to new-style codelists would mean making a new version of each codelist, which has implications for any studies or individuals that might be using them.  We don't currently have a straightforward way to notify consumers of codelists.

The proposed short term solution is to leave current dm+d codelists as they are, and have cohort-extractor/databuilder add in the previous/new VMP IDs.  This includes the following tasks:
 
- [ ] Add an API endpoint to OpenCodelists that returns a mapping of current:previous VMP IDs #1460 
- [ ] Job server proxies this so that it can be retrieved on the secure server 
- [ ] The mapping is used to build a new database table/view that does the expansion of the medication table to include alternative (prev/subsequent) codes (TBC where - as a job-runner script in the first instance?)
- [ ] Update cohort-extractor methods that use the Medication table (`with_these_medications`**) to use the new expanded medication table instead
- [ ]  Similarly, in databuilder, use the new expanded medications table (currently `beta.tpp.medications`.)
- [ ] A release of dm+d only has the ability to track previous ids for previous ids if the previous ID is still a current code (otherwise it can't be looked up in the release DB).  Currently all but 2 VMP IDs have previous codes that are not still current.  We should be able to check against older releases from OpenPrescribing to see if codes change multiple times - if they do, we might still be missing codes.  Since we will now be tracking releases, we do have a way to maintain the previous code mapping from now on.  
- [ ] All dm+d codelists on OpenCodelists need to be accompanied by a disclaimer that says that there could be previous or new codes and that OpenSafely will include them
- [x] #1388 Even though we're not making dm+d codelists new-style codelists just yet, we should have a way to check newly uploaded ones to ensure they're valid and consistent with the latest dm+d coding system release (that means we can also assign a dm+d release to a new dm+d codelist version and have a record of the release at the time the version was created). 
- [ ] Regularly import dm+d data (in the short term, this can be manual, with a slack reminder).  After the import is complete, also run the script to update the medications table on the server.  If possible, automate it with the available API #1469 

** Somewhat confusingly, `with_these_medications` in cohort-extractor [requires a snomedct codelist](https://github.com/opensafely-core/cohort-extractor/blob/fe22cdb3bf873aab9eaa00a35c65b7d6e112fc4f/cohortextractor/tpp_backend.py#L1063), and will error if it encounters a codelist with any other coding system.  It does, however, look up the codes in the TPP MedicationIssue table by a `DMD_ID` field (via the MedicationDictionary table, which uses Multilex drug ids).   In fact, studies use dm+d codelists and assign the coding system as snomedct...I'm not sure why (and since dm+d ids are always snomedct codes, it doesn't affect anything)

**Comment by rebkwok** [comment]
I think @inglesp probably has a better answer to why it's more complicated to update all the codelists in OpenCodelists.  
We can contact authors easily, and users who are part of an organisation the codelist belongs to, but consumers could be wider than that?
We'd also need to do this on a weekly basis, since dm+d is released weekly

**Comment by inglesp** [comment]
Thanks for writing this up Becky.

I think there's just one missing task: regularly import latest dm+d release.  This could be manual for now (with a Slack reminder?).

Additionally, the databuilder work will be a bit different to cohort-extractor.  Instead of `with_these_medications`, we'll have to check for queries against columns with a `DMDCode` type.  (Currently this is just used in the `beta.tpp.medications` table.)

Could you update the checklist with these?

I think the work should be easy to parallelise.  Should we have a call to discuss how we divide up the work?

**Comment by Jongmassey** [comment]
>This could be manual for now (with a Slack reminder?).

I'm subscribed on TRUD and get an email every Monday and I tend to download the latest release for my own dmd-version-comparison pet project. If others subbed to the release then that could be a way of spreading the remindering


>A github action fetches the most recent mapping from opencodelists on a weekly basis, updates and commits it if it's changed, and opens a PR (and possibly automerges, although the PR would be the only prompt to update the images on the server)

Could cohortextractor/databuilder do an HTTP get to github.com/opensafely/blah/dmd_vmp_mappings_latest.csv to avoid this?

**Comment by rebkwok** [comment]
> I'm subscribed on TRUD and get an email every Monday and I tend to download the latest release for my own dmd-version-comparison pet project. If others subbed to the release then that could be a way of spreading the remindering

I am too, but a slack reminder means it's not dependent on someone who gets the emails being around to do the updating (this way we have both, I guess)

**Comment by rebkwok** [comment]
The plan we discussed today (not yet updated in the checklist above):
1) OpenCodelists has an API endpoint to retrieve a mapping of DMD current code to previous code(s)
2) Job server proxies this (somehow) so that it can be retrieved on the secure server
3) The mapping is used to build a new database table/view that does the expansion of the medication table to include alternative (prev/subsequent) codes (TBC where - job-runner?)
4) Changes to cohort-extractor and databuilder should be minimal and not involve much more than updating the medication queries to query the new table
5) Some mechanism for alerting if the expanded medication table doesn't build successfully

**Comment by Jongmassey** [comment]
SQL thoughts and quick tests:

```SQL
-- create tables
CREATE TABLE dbo.dmd_latest(
  dmd_id bigint NOT NULL PRIMARY KEY
);
CREATE TABLE dbo.dmd_previous(

  previous_dmd_id bigint NOT NULL PRIMARY KEY,
  dmd_id bigint NOT NULL FOREIGN KEY REFERENCES dmd_latest(dmd_id)
);
CREATE TABLE dbo.MedicationDictionary(
    multilex_id int not null primary key,
    dmd_id bigint not null
)
CREATE TABLE dbo.MedicationIssue(
    issue_id int not null primary key IDENTITY(1,1),
    issue_date datetime not null,
    patient_id int not null,
    multilex_id int not null FOREIGN KEY REFERENCES dbo.MedicationDictionary(multilex_id)
)

-- insert test data
INSERT dbo.dmd_latest
    (dmd_id)
VALUES
    (1),
    (2),
    (3),
    (4),
    (5);

INSERT dbo.dmd_previous
    (dmd_id,previous_dmd_id)
VALUES
    (2, 22),
    (3, 33),
    (3, 333),
    (4, 44),
    (4, 444),
    (4, 4444),
    (5, 55),
    (5, 555),
    (5, 5555),
    (5, 55555);

INSERT dbo.MedicationDictionary
    (multilex_id,dmd_id)
VALUES
    (91, 1),
    (92, 22),
    (93, 333),
    (94, 4444),
    (95, 55555);

INSERT dbo.MedicationIssue(
    multilex_id,patient_id,issue_date
)
VALUES
    (91, 1,'2021-01-01'),
    (92, 1,'2021-01-02'),
    (93, 1,'2021-01-03'),
    (94, 1,'2021-01-04'),
    (95, 1,'2021-01-05');

-- codelist temp table
CREATE TABLE #codelist(dmd_id bigint NOT NULL PRIMARY KEY)
INSERT #codelist(dmd_id)
VALUES
    (1),
    (22),
    (3),
    (33),
    (44),
    (444),
    (4444),
    (5);
```
Using the existing way that cohortextractor does it

```SQL
SELECT mi.* 
FROM dbo.MedicationIssue mi
JOIN dbo.MedicationDictionary md
    ON mi.multilex_id = md.multilex_id
JOIN #codelist c
    ON c.dmd_id = md.dmd_id;
```

Yields

| issue_id | issue_date | patient_id | multilex_id |
|---|---|---|---|
| 1 | 2021-01-01 00:00:00.000 | 1 | 91 |
| 2 | 2021-01-02 00:00:00.000 | 1 | 92 |
| 4 | 2021-01-04 00:00:00.000 | 1 | 94 |

missing 3 and 5

Using a simple inner join between the new and existing lookup tables

```sql
SELECT mi.*
FROM dbo.MedicationIssue mi
JOIN dbo.MedicationDictionary md
    ON mi.multilex_id = md.multilex_id
JOIN dbo.dmd_previous dp
    ON md.dmd_id = dp.previous_dmd_id
    OR md.dmd_id = dp.dmd_id
JOIN #codelist c
    ON c.dmd_id = dp.previous_dmd_id
    OR c.dmd_id = dp.dmd_id;
```

Yields
| issue_id | issue_date | patient_id | multilex_id |
|---|---|---|---|
| 2 | 2021-01-02 00:00:00.000 | 1 | 92 | 
| 3 | 2021-01-03 00:00:00.000 | 1 | 93 | 
| 4 | 2021-01-04 00:00:00.000 | 1 | 94 | 
| 5 | 2021-01-05 00:00:00.000 | 1 | 95 | 

No dupes but misses 1 because has not had VMP id replaced
If we add a row into previous such that it has a full set of ids for each VMP (this means we don't actually need dbo.dmd_latest)

```SQL
INSERT dbo.dmd_previous
    (dmd_id,previous_dmd_id)
VALUES
    (1, 1);
```

Try simple approach again

```SQL
SELECT mi.*
FROM dbo.MedicationIssue mi
JOIN dbo.MedicationDictionary md
    ON mi.multilex_id = md.multilex_id
JOIN dbo.dmd_previous dp
    ON md.dmd_id = dp.previous_dmd_id
    OR md.dmd_id = dp.dmd_id
JOIN #codelist c
    ON c.dmd_id = dp.previous_dmd_id
    OR c.dmd_id = dp.dmd_id;
```
| issue_id | issue_date | patient_id | multilex_id |
|---|---|---|---|
| 1 | 2021-01-01 00:00:00.000 | 1 | 91 |
| 2 | 2021-01-02 00:00:00.000 | 1 | 92 |
| 3 | 2021-01-03 00:00:00.000 | 1 | 93 |
| 4 | 2021-01-04 00:00:00.000 | 1 | 94 |
| 5 | 2021-01-05 00:00:00.000 | 1 | 95 |

complete result set with no dupes
Double-check with same medication being issued multiple times
```SQL
INSERT dbo.MedicationIssue(
    multilex_id,patient_id,issue_date
)
VALUES
    (91, 1,'2021-02-01'),
    (91, 1,'2021-03-01');
```
Try simple again

```SQL
SELECT mi.*
FROM dbo.MedicationIssue mi
JOIN dbo.MedicationDictionary md
    ON mi.multilex_id = md.multilex_id
JOIN dbo.dmd_previous dp
    ON md.dmd_id = dp.previous_dmd_id
    OR md.dmd_id = dp.dmd_id
JOIN #codelist c
    ON c.dmd_id = dp.previous_dmd_id
    OR c.dmd_id = dp.dmd_id;
```

| issue_id | issue_date | patient_id | multilex_id |
|---|---|---|---|
| 1 | 2021-01-01 00:00:00.000 | 1 | 91 |
| 2 | 2021-01-02 00:00:00.000 | 1 | 92 |
| 3 | 2021-01-03 00:00:00.000 | 1 | 93 |
| 4 | 2021-01-04 00:00:00.000 | 1 | 94 |
| 5 | 2021-01-05 00:00:00.000 | 1 | 95 |
| 6 | 2021-02-01 00:00:00.000 | 1 | 91 |
| 7 | 2021-03-01 00:00:00.000 | 1 | 91 |

still no dupes or missing

If you wanted to minimise code changes to cohortextractor or databuilder maybe a TVF would help?

```SQL
CREATE FUNCTION fn_MedicationDictionary (
    @dmd_id bigint
)
RETURNS TABLE
AS
RETURN
    SELECT md.multilex_id
    FROM dbo.MedicationDictionary md
    JOIN dbo.dmd_previous dp
        ON md.dmd_id = dp.previous_dmd_id
        OR md.dmd_id = dp.dmd_id
    WHERE dp.previous_dmd_id = @dmd_id
    OR dp.dmd_id = @dmd_id;
```
So instead of 

```SQL
SELECT mi.* 
FROM dbo.MedicationIssue mi
JOIN dbo.MedicationDictionary md
    ON mi.multilex_id = md.multilex_id
JOIN #codelist c
    ON c.dmd_id = md.dmd_id; 
```

It would be

```SQL
SELECT mi.* 
FROM #codelist c
CROSS APPLY dbo.fn_MedicationDictionary(c.dmd_id) md
JOIN dbo.MedicationIssue mi
    ON mi.multilex_id = md.multilex_id;
```

| issue_id | issue_date | patient_id | multilex_id |
|---|---|---|---|
| 1 | 2021-01-01 00:00:00.000 | 1 | 91 |
| 2 | 2021-01-02 00:00:00.000 | 1 | 92 |
| 3 | 2021-01-03 00:00:00.000 | 1 | 93 |
| 4 | 2021-01-04 00:00:00.000 | 1 | 94 |
| 5 | 2021-01-05 00:00:00.000 | 1 | 95 |
| 6 | 2021-02-01 00:00:00.000 | 1 | 91 |
| 7 | 2021-03-01 00:00:00.000 | 1 | 91 |

Not sure if that's any easier and would need to check the performance implications

**Comment by inglesp** [comment]
Thanks for this @Jongmassey.  I'm going to call your version the "extra join approach".

As far I as I can tell, we can achieve the same by including all possible past-and-present codes in the codelist, and using the existing SQL.  I'll call this the "extended codelist approach".  In SQLite:

```
CREATE TABLE codelist2(dmd_id NOT NULL PRIMARY KEY);
INSERT INTO codelist2(dmd_id)
VALUES
    (1),
    (2),
    (22),
    (3),
    (33),
    (333),
    (4),
    (44),
    (444),
    (4444),
    (5),
    (55),
    (555),
    (5555),
    (55555);

SELECT mi.* 
FROM MedicationIssue mi
JOIN MedicationDictionary md
    ON mi.multilex_id = md.multilex_id
JOIN codelist2 c
    ON c.dmd_id = md.dmd_id;

issue_date  multilex_id
----------  -----------
2021-01-01  91         
2021-01-02  92         
2021-01-03  93         
2021-01-04  94         
2021-01-05  95  
```

Do we also need to consider the case where `MedicationDictionary` contains records for both the previous and the current version of a VMP?  If so, then there's a problem with the extra join approach:

```
INSERT INTO MedicationDictionary
    (multilex_id,dmd_id)
VALUES
    (96, 5);  -- there's already an entry for (95, 55555), so now there's an entry for both the previous and current version of this VMP
INSERT INTO MedicationIssue(
    multilex_id,issue_date
)
    (96,'2021-01-06');

SELECT mi.*
FROM MedicationIssue mi
JOIN MedicationDictionary md
    ON mi.multilex_id = md.multilex_id
JOIN dmd_previous dp
    ON md.dmd_id = dp.previous_dmd_id
    OR md.dmd_id = dp.dmd_id
JOIN codelist c
    ON c.dmd_id = dp.previous_dmd_id
    OR c.dmd_id = dp.dmd_id;

issue_date  multilex_id
----------  -----------
2021-01-01  91         
2021-01-02  92         
2021-01-03  93         
2021-01-04  94         
2021-01-05  95         
2021-01-06  96         
2021-01-06  96         
2021-01-06  96         
2021-01-06  96         
2021-01-06  96  
```

However, there's no problem with the extended codelist approach:

```
SELECT mi.* 
FROM MedicationIssue mi
JOIN MedicationDictionary md
    ON mi.multilex_id = md.multilex_id
JOIN codelist2 c
    ON c.dmd_id = md.dmd_id;

issue_date  multilex_id
----------  -----------
2021-01-01  91         
2021-01-02  92         
2021-01-03  93         
2021-01-04  94         
2021-01-05  95         
2021-01-06  96 
```

Even if we don't need to worry about `MedicationDictionary` containing records for both the previous and the current version of a VMP, I'd argue that the extended codelist approach is worth considering, since it does not introduce any risks to performance.

Finally, last week we talked about double counting.  Given that `MedicationDictionary.multilex_id` is unique, I don't think this is a problem.  But I'd like to talk it through to be sure.

**Comment by rebkwok** [comment]
> we can achieve the same by including all possible past-and-present codes in the codelist, and using the existing SQL

There's some pre-amble to this, isn't there?  We need to add the extra past-and-present codes to the codelist somewhere.  If the codelists themselves aren't changing, where does cohort-extractor get the mapped codes from?  Presumably still our proposed opencodelists endpoint?  Would the extended codelist approach still involve using that endpoint to create another database table with the mapping from current-to-previous, but we use that to build the codelist table rather than to join for the medications query?  Is it that simple for databuilder as well?

**Comment by inglesp** [comment]
> There's some pre-amble to this, isn't there?

Yes.  Cohort-extractor/databuilder would still need to get the mapped codes from OpenCodelists, and it probably makes sense to store the mapping in a database table.

**Comment by evansd** [comment]
I fear that the "extended codelist approach" is a non-starter in Data Builder, for several reasons. Effectively it violates the semantic model so it's no longer possible to tell a consistent story about what your query is actually doing.

For instance, it becomes possible to query for all prescriptions matching codes A, B or C; fetch the most recent; ask for the corresponding code, and get D (because behind the scenes your query has been expanded to include additional codes). 

Or suppose you use a query which fetches a code for each patient, and then a query which finds the first time that code appeared on each patient's record. If we're consistently treating old and new codes as equivalent then we ought to do so here as well. But there's no codelist here to expand.

I don't see any way around having a view on the MedicationIssue table which contains duplicate rows (one for each each version of the code). This would have to come with clear documentation that if you wanted to use it to count things you have to use `count_distinct()` on the `medication_issue_id` column.

**Comment by Jongmassey** [comment]
> Effectively it violates the semantic model so it's no longer possible to tell a consistent story about what your query is actually doing.

Unless the semantics of mapping via multilex becomes a native databuilder concept?

**Comment by Jongmassey** [comment]
Or what if the query "lies" by returning the ID queried by the user, not the one that's in the current mapping held by TPP?

**Comment by inglesp** [comment]
Done in https://github.com/opensafely-core/opencodelists/pull/1460, https://github.com/opensafely-core/cohort-extractor/pull/896, https://github.com/opensafely-core/cohort-extractor/pull/896.
